.github/workflows/ci.yml

Fixes: Removes Docker ARM platform builds from CI as requested in #17

Only build docker for linux #17

---

scratch.py
src/nwp_consumer/cmd/main.py
src/nwp_consumer/internal/outputs/localfs/client.py
src/nwp_consumer/internal/outputs/s3/client.py
src/nwp_consumer/internal/service/service.py
src/nwp_consumer/internal/service/test_service.py

In order to allow backwards compatibility for the current consumer, modify the behavior of the CreateLatest function to save both zipped and regular zarrs.

Save both zarr and zipped zarr

---

src/nwp_consumer/internal/config/config.py
src/nwp_consumer/internal/outputs/s3/client.py

Addresses #20. This works assuming that the s3fs `S3FileSystem` automatically tries to access default connection values from the environment when `key` and `secret` are `None`.

Set AWS credentials as optional env vars, use defaults if not set

---

README.md
pyproject.toml
src/nwp_consumer/cmd/main.py
src/nwp_consumer/internal/config/config.py
src/nwp_consumer/internal/inputs/ceda/_models.py
src/nwp_consumer/internal/inputs/ceda/client.py
src/nwp_consumer/internal/inputs/ceda/test_client.py
src/nwp_consumer/internal/inputs/metoffice/_models.py
src/nwp_consumer/internal/inputs/metoffice/client.py
src/nwp_consumer/internal/inputs/metoffice/test_client.py
src/nwp_consumer/internal/outputs/localfs/client.py
src/nwp_consumer/internal/outputs/s3/client.py
src/nwp_consumer/internal/outputs/s3/test_client.py
src/nwp_consumer/internal/service/service.py
src/nwp_consumer/internal/service/test_service.py
src/test_integration/test_inputs_integration.py
src/test_integration/test_service_integration.py

National forecaster was failing as it expected y to scan negatively. This resolves that, as well as the wrong shape failure seen in the regular forecaster by reordering the variables.
See #24

Modify order of variables in dataset, scan y backwards

---

src/nwp_consumer/internal/inputs/metoffice/client.py

Related to #45. Currently the metoffice NWP data is saved out with increasing x and y coords. `ocf_datapipes` assumes it should have increasing x and decreasing y. This reorganises the data so y is decreasing

y-axis in desceding order

---

src/nwp_consumer/cmd/main.py
src/nwp_consumer/internal/config/env.py
src/nwp_consumer/internal/inputs/ecmwf/mars.py
src/nwp_consumer/internal/inputs/icon/client.py
src/test_integration/test_service_integration.py

Integration tests currently timeout on github runners due to testing download of entire daily datasets. This PR implements a the idea of a "parameter group" to source clients that can be set to "default" or "basic". "basic" only requests a small subset of parameters to speed up the total time of the integration test.

Create basic parametersets for shorter integration testing

---

src/nwp_consumer/internal/outputs/huggingface/client.py
src/nwp_consumer/internal/service/service.py

Huggingface does not like simulaneous file pushes as it is a version-contril based system thta checks the head commit hasn't changed before every push. Since this process is not time-critical, revert it to be done in a single-threaded manner.

Make storing single-threaded to fix hugginface commit issues

---

src/nwp_consumer/cmd/main.py
src/nwp_consumer/internal/outputs/huggingface/client.py
src/nwp_consumer/internal/service/service.py
src/test_integration/test_service_integration.py

Huggingface uploads files when given an absolute path but is unable to find said files when given the same path. As such, remove the possibility of adding leading slashes to any paths being stored in huggingface.

Guard against absolute paths in huggingface

---

src/nwp_consumer/internal/inputs/ecmwf/mars.py
src/nwp_consumer/internal/outputs/huggingface/client.py

Ensure hanging isn't occuring at read time on ECMWF temporary file

Explicitly open temp file for writing and close before reading

---

src/nwp_consumer/internal/outputs/huggingface/client.py
src/nwp_consumer/internal/outputs/huggingface/test_client.py
src/nwp_consumer/internal/service/service.py

Huggingface cannot download a single file to a path you want - rather, it recreates the path within the repo in a directory of your specifying. This commit ensures that those paths are specified when dealing with downloaded files from huggingface.

Ensure huggingface stores temporary files in the right location

---

src/nwp_consumer/internal/inputs/icon/client.py

Icon data is replaced on the server by new runs, but until that point it is still accessible, even if it corresponds to an init time of yesterday. This enables that data to be retrieved.

Enable accessing ICON data under 24 hours old

---

README.md

This PR fixes an issue with `pip install -e .[dev]` throwing an error when using zsh on MacOS. See https://github.com/mu-editor/mu/issues/852 for more details about the problem.
Install dev dependencies on a mac using `pip install -e ".[dev]"` does not throw an error.
*I marked tasks that are not applicable as checked.*

Add quotation for pip install dev

---

src/nwp_consumer/cmd/main.py
src/nwp_consumer/internal/config/__init__.py
src/nwp_consumer/internal/config/env.py
src/nwp_consumer/internal/inputs/ceda/client.py
src/nwp_consumer/internal/inputs/ceda/test_client.py
src/nwp_consumer/internal/inputs/ecmwf/test_mars.py
src/nwp_consumer/internal/inputs/icon/test_client.py
src/nwp_consumer/internal/inputs/metoffice/test_client.py
src/nwp_consumer/internal/inputs/noaa/test_aws.py
src/nwp_consumer/internal/service/service.py
src/test_integration/test_service_integration.py

Can use the Env var `DASK_SCHEDULER_ADDRESS` to specify an address to pass to a `dask.distributed` client.

Enable using dask distributed client via configuration

---

src/nwp_consumer/internal/inputs/ecmwf/mars.py
src/nwp_consumer/internal/inputs/ecmwf/s3.py
src/nwp_consumer/internal/inputs/ecmwf/test_s3.py

Adds in to the test case a check that the rename map correctly results in the temperature variable being encoded in the zarr with "t".

test(ecmwf s3): Temperature variable renaming

---

src/nwp_consumer/internal/inputs/icon/client.py

Enables "single-level" and "multi-level" to be used as the parameter group for icon

feat(icon client): sl/ml parameter groups

---

src/nwp_consumer/internal/inputs/ecmwf/s3.py
src/nwp_consumer/internal/outputs/s3/client.py
src/nwp_consumer/internal/service/consumer.py

Fixes for bugs brought up by the implementation of the meteomatics live service. See #142

fix(s3): Guard against ls errors

---

src/nwp_consumer/internal/inputs/ceda/client.py
src/nwp_consumer/internal/inputs/ceda/test_client.py
src/nwp_consumer/internal/outputs/s3/client.py
src/nwp_consumer/internal/outputs/s3/test_client.py

feat(s3): Don't upload if file of same name and size already exists

---

pyproject.toml
src/nwp_consumer/cmd/main.py

Minor Update to the code which adds Sentry for a better error detection
Stems from the PR: https://github.com/openclimatefix/ocf-infrastructure/issues/540
_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

Code update to add sentry

---

.github/workflows/ci.yml
pyproject.toml
src/nwp_consumer/internal/inputs/metoffice/client.py
src/nwp_consumer/internal/inputs/metoffice/test_client.py

- put test back in
- same error as we see in production on 0.5.27
- rename variables if there
Helps with #185 
Ci tests

Fix for sdswrf and  sdlwrf

---

.github/workflows/main_ci.yml
.github/workflows/tagged_ci.yml

Fixes some incorrect actions versions in the workflow files

fix(ci): Correct versioning of actions

---

src/nwp_consumer/internal/services/archiver_service.py

Enables the archiver service to handle the fact that fetch_init_data returns a list of xarray datasets, not just one.

fix(archiver): Allow for list of dataarrays

---

src/nwp_consumer/internal/entities/coordinates.py
src/nwp_consumer/internal/entities/modelmetadata.py
src/nwp_consumer/internal/entities/tensorstore.py
src/nwp_consumer/internal/entities/test_tensorstore.py
src/nwp_consumer/internal/repositories/raw_repositories/ceda_ftp.py
src/nwp_consumer/internal/repositories/raw_repositories/ecmwf_realtime.py
src/nwp_consumer/internal/services/consumer_service.py

In response to my own comments on PR #214 I've made some changes.
Since chunking is an IO decision to do with the written data and not the read in data, the chunking is relevant only to the write_to_region and create_suitable_store functions. In order to enable for different chunking from the default for the repositories that require it due to the natire of their files, overrides can be set in the repository metadata.

fix(coordinate): Log warning on unsafe regional writes

---

src/nwp_consumer/internal/entities/coordinates.py
src/nwp_consumer/internal/entities/modelmetadata.py
src/nwp_consumer/internal/entities/tensorstore.py
src/nwp_consumer/internal/entities/test_tensorstore.py
src/nwp_consumer/internal/repositories/raw_repositories/ceda_ftp.py
src/nwp_consumer/internal/repositories/raw_repositories/ecmwf_realtime.py
src/nwp_consumer/internal/services/consumer_service.py

- Only uses processes, not threads in the cloud
- reduce chunks from 8 in lat, lon and variables to 2, this reduce the numbers of files by 64. Down from ~50,000 to ~700. This makes writing to s3 much quicker. Reduces the run time from 1 hour to 10 mins. 
- For archive, all the options default to what they were before
https://github.com/openclimatefix/ocf-infrastructure/issues/697

Speed up on, saving to cloud

---

src/nwp_consumer/internal/repositories/raw_repositories/noaa_s3.py

Reduce delay to 5 hours.
By checking a few date stamps, the files are ready >3 and <5 hours. So setting the delay at 5 hours, means we should get all the files
helps with https://github.com/openclimatefix/ocf-infrastructure/issues/697

reduce delay to 5 hours

---

src/nwp_consumer/internal/entities/coordinates.py
src/nwp_consumer/internal/entities/modelmetadata.py
src/nwp_consumer/internal/repositories/raw_repositories/ecmwf_mars.py
src/nwp_consumer/internal/repositories/raw_repositories/ecmwf_realtime.py
src/nwp_consumer/internal/services/consumer_service.py

Enables pulling full ensemble data from MARS.

feat(ecmwf): Add full ensemble model

---

src/nwp_consumer/internal/repositories/raw_repositories/mo_datahub.py

Closes #227 
> [!Note]
> Requires a modification to the MODEL environment variable in terraform for metoffice india data to change from `um-global-10km` to `um-global-india`.
> It won't break immediately as this also updates the default, but will silence the warnings.

fix(consumer): Chunking error

---

src/nwp_consumer/internal/repositories/raw_repositories/noaa_s3.py

GFS datasets contain both `sdwe` and `sde` - we only want `sde`, measured in meters.

fix(gfs): Remove unwanted clashing variable

---

src/nwp_consumer/internal/entities/tensorstore.py
src/nwp_consumer/internal/services/consumer_service.py

Checks for NaNs in created store, deletes store if any failure occurs during processing.

feat(consumer): NaN check, delete created store on any failure

---

src/nwp_consumer/internal/entities/modelmetadata.py
src/nwp_consumer/internal/entities/tensorstore.py
src/nwp_consumer/internal/repositories/raw_repositories/ecmwf_realtime.py

ECMWF live only goes to 60 north, so restrct it to that
This means ECMWF doesnt repeat itself
Also reduce nan margins

add north60 as an option

---

src/nwp_consumer/internal/repositories/raw_repositories/mo_datahub.py

Works when tested locally.
Makes METOFFICE_DATASPEC an env option that defaults to 1.1.0.

fix(metoffice): Dataspec parameter to env var
