.github/workflows/ci.yml
Containerfile
src/nwp_consumer/internal/config/test_config.py
src/nwp_consumer/internal/outputs/s3/client.py
src/test_integration/test_service_integration.py

Aids in resolving #15. Docker caching speeds up building of containers to ~3mins.

Improve consistency and speed of CI via seperate venv job

---

src/nwp_consumer/internal/inputs/metoffice/client.py

-  change `x` to `y` to ints
CI test

make sure y and x as ints

---

src/nwp_consumer/internal/inputs/metoffice/client.py
src/nwp_consumer/internal/inputs/metoffice/test_client.py

fix wind direction names
followed comment on code, and correct them
CI tests

fix wind names

---

src/nwp_consumer/internal/inputs/metoffice/client.py

Fix for y values the wrong way round
- dont reindex by inverting y, and dont flip y values
Fixes #44 
- CI tests
- TODO run locally

try not flipping values

---

src/nwp_consumer/internal/outputs/huggingface/client.py
src/nwp_consumer/internal/outputs/huggingface/test_client.py

Huggingface client was not working with the fspec implementation, so this MR modifies it to use the huggingface API instead.

Modify the huggingface client to use the huggingface api

---

src/nwp_consumer/cmd/main.py
src/nwp_consumer/internal/service/service.py

Enables storing raw data in a different place. Creates tech debt tracked by https://github.com/openclimatefix/nwp-consumer/issues/107

Enable optional separate raw storer

---

ARCHITECTURE.md

Add ARCHITECTURE.md diagram

---

.github/workflows/ci.yml
src/test_integration/test_service_integration.py

Only writes docker buildcache on default branch to prevent polluting the cache from branch work.

feat(ci): Change cache strategy

---

src/nwp_consumer/internal/inputs/ecmwf/mars.py

Part of what is required for https://github.com/openclimatefix/dagster-dags/issues/99

feat(ecmwf): Add india area to ecmwf

---

src/nwp_consumer/internal/config/env.py
src/nwp_consumer/internal/inputs/noaa/aws.py
src/nwp_consumer/internal/inputs/noaa/test_aws.py

Enables GFS to be pulled live from the AWS archive

fix(gfs): Use AWS and fix for live

---

src/nwp_consumer/internal/inputs/ecmwf/s3.py
src/nwp_consumer/internal/inputs/ecmwf/test_s3.py
src/nwp_consumer/internal/outputs/localfs/client.py

fix(ecmwf-s3): Actually drop unwanted coordinates

---

src/nwp_consumer/internal/inputs/noaa/aws.py

Changes GFS model to the 1degree and only pulls every third step to match the data pulled by Herbie for training

fix(gfs): Match pulled data with training

---

src/nwp_consumer/internal/inputs/noaa/aws.py

Add some gfs logging
Might help with #166 
CI tests (no actual logic change)

Add logging gfs

---

src/nwp_consumer/__init__.py

add pathname to logger
Fixes #
CI tests

add pathname in logging

---

src/nwp_consumer/internal/inputs/ecmwf/s3.py

Remove chunking on step for ecmwf s3
Might help with #176 
CI tests (some fail, not sure to this)

remove chunking on s3

---

src/nwp_consumer/internal/inputs/ecmwf/s3.py

ECMWF are providing us with modified realtime data, this PR enables reading it in the consumer.

feat(ecmwf): Enable support for new realtime datasets

---

src/nwp_consumer/internal/repositories/raw_repositories/ecmwf_realtime.py

Fix for ECMWF, make delay 6 hours and 15 minutes
CI tests

delay ecmwf by 6 hours and 15 mins #218

---

src/nwp_consumer/internal/repositories/raw_repositories/ecmwf_mars.py

fix(ecmwf-mars): Add ensemble_member dimension even when in container

---

src/nwp_consumer/internal/entities/tensorstore.py

allow for 20% nans
Fixes #
CI tests

20% nans in nwp is ok

---

src/nwp_consumer/internal/entities/modelmetadata.py
src/nwp_consumer/internal/repositories/raw_repositories/ecmwf_realtime.py

make sure last nwp step of ECMWF is included

change < to <= for ecmwf
